training:
  gpu: !env CUDA_VISIBLE_DEVICES # Get the value of env variable CUDA_VISIBLE_DEVICES
  epochs: 18
  batch_size: 100

  optimizer:
    !obj torch.optim.SGD : {lr : 0.001}

  scheduler:
    !obj torch.optim.lr_scheduler.MultiStepLR : {milestones: [2, 6, 10, 14]}

  loss:
    !obj torch.nn.BCELoss : {}

model: !include "./models/my_model.yaml"

transforms:
  - !obj transforms.Normalize : {}
  - !obj transforms.Noise : {}
  - !obj transforms.RandomFlip : {probability: 0.5}